repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
        name: check for added large files
        description: prevents giant files from being committed
        entry: check-added-large-files
        language: python
        stages:
          - commit
          - push
          - manual
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: gitlint
        description: Checks your git commit messages for style.
        language: python
        additional_dependencies: ["./gitlint-core[trusted-deps]"]
        entry: gitlint
        args: [--staged, --msg-filename]
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: ['--branch', 'master']
  - repo: https://github.com/milin/giticket
    rev: v1.4
    hooks:
      - id: giticket
        args: ['--mode=regex_match', '--format=[{ticket}] {commit_msg}']
