name: Build and Publish Helm Chart

on:
  push:
    branches:
      - main
      - develop
      - feature/add_github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'


      - name: Helm lint
        run: |
          helm lint helm/ph-ee-engine
        working-directory: ${{ github.workspace }}

      - name: Package Helm Chart
        run: |
          helm dependency update helm/ph-ee-engine
          helm package helm/ph-ee-engine --destination $(Build.ArtifactStagingDirectory)

      - name: Publish Helm Chart
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          echo "Publishing Helm chart..."
          # You can add your logic here to publish the Helm chart.
          # Replace this with your actual publish steps.
        working-directory: ${{ github.workspace }}
