name: Build and Package Helm Chart

on:
  push:
    branches:
      - main
      - develop
      - feature/add_github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Package Helm Chart
        run: |
          # Lint
          helm dependency update helm/ph-ee-engine
          helm lint helm/ph-ee-engine
          # Package Helm chart
          helm package helm/ph-ee-engine --destination ./artifacts
          # Display the contents of the artifacts directory
          ls -l ./artifacts

      - name: Publish Helm Chart
        uses: actions/upload-artifact@v2
        with:
          name: paymenthub
          path: ./artifacts/*
